# Single responsibility: Trivy container image scan + upload SARIF
name: Trivy Image Scan
description: Scan container image with Trivy and upload SARIF

inputs:
  image-ref:
    required: true

  severity:
    required: false
    default: 'CRITICAL,HIGH'

  fail-on-severity:
    description: 'Fail pipeline if this severity is found'
    required: false
    default: 'CRITICAL'
runs:
  using: composite
  steps:
    - name: Run Trivy image scan (console)
      uses: aquasecurity/trivy-action@v0.36.0
      with:
        image-ref: ${{ inputs.image-ref }}
        format: 'table'
        severity: ${{ inputs.fail-on-severity }}
        exit-code: '1'

#    - name: Run Trivy image scan (SARIF)
#      uses: aquasecurity/trivy-action@v0.24.0
#      with:
#        image-ref: ${{ inputs.image-ref }}
#        format: 'sarif'
#        output: 'trivy-image-results.sarif'
#        severity: ${{ inputs.severity }}

#    - name: Upload Trivy image SARIF
#      uses: github/codeql-action/upload-sarif@v3
#      if: always()
#      with:
#        sarif_file: 'trivy-image-results.sarif'
