name: SonarQube Scan
description: Download coverage (se existir) e roda SonarQube scan

inputs:
  coverage-path:
    required: false
    default: 'coverage.xml'
  sonar-args:
    description: 'Extra SonarQube args (e.g. PR key, branch)'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Download coverage (opcional)
      uses: actions/download-artifact@v4
      with:
        name: coverage
      continue-on-error: true

    - name: Definir args de coverage
      shell: bash
      run: |
        if [ -f "${{ inputs.coverage-path }}" ]; then
          echo "COVERAGE_ARGS=-Dsonar.python.coverage.reportPaths=${{ inputs.coverage-path }}" >> $GITHUB_ENV
        else
          echo "COVERAGE_ARGS=" >> $GITHUB_ENV
        fi

    - name: SonarCloud Scan
      uses: SonarSource/sonarqube-scan-action@v2
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.projectKey=${{ github.repository }}
          -Dsonar.sources=.
          ${{ env.COVERAGE_ARGS }}
          ${{ inputs.sonar-args }}