name: CI - Pull Request

on:
  workflow_call:
    inputs:
      coverage-exclusions:
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  # -----------------------------
  # 1️⃣ Trivy FS
  # -----------------------------
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: TourinhoM/org-ci-platform/.github/actions/trivy-fs@v1

  # -----------------------------
  # 2️⃣ Secret Scan (gitleaks)
  # -----------------------------
  secret-scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: TourinhoM/org-ci-platform/.github/actions/secret-scan@v1

  # -----------------------------
  # 3️⃣ SonarQube
  # -----------------------------
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: trivy-fs
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: TourinhoM/org-ci-platform/.github/actions/unit-test@v1
      - uses: TourinhoM/org-ci-platform/.github/actions/sonarqube@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          sonar-organization: ${{ vars.SONAR_ORG }}
          coverage-exclusions: ${{ vars.SONAR_COVERAGE_EXCLUSIONS }}
          sonar-args: ""

  # -----------------------------
  # 4️⃣ Semantic Commit Check
  # -----------------------------
  semantic-commit-check:
    name: Semantic Commit Check
    runs-on: ubuntu-latest
    needs: sonarqube
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: TourinhoM/org-ci-platform/.github/actions/semantic-commit-check@v1