name: CI - Push

on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
      coverage-exclusions:
        required: false
        type: string
    secrets:
      SONAR_TOKEN:
        required: false

jobs:

  # -----------------------------
  # 1️⃣ Trivy FS
  # -----------------------------
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: TourinhoM/org-ci-platform/.github/actions/trivy-fs@main

  # -----------------------------
  # 2️⃣ SonarQube (não roda para tag)
  # -----------------------------
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs: trivy-fs
    if: "!startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v5
      - uses: TourinhoM/org-ci-platform/.github/actions/unit-test@main
      - uses: TourinhoM/org-ci-platform/.github/actions/sonarqube@main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          sonar-organization: ${{ vars.SONAR_ORG }}
          coverage-exclusions: ${{ inputs.coverage-exclusions }}
          sonar-args: ""

  # -----------------------------
  # 3️⃣ Prepare Image
  # -----------------------------
  prepare-image:
    name: Prepare image
    runs-on: ubuntu-latest
    needs: [trivy-fs, sonarqube]
    outputs:
      image_repo: ${{ steps.prepare.outputs.repo }}
      image_tag: ${{ steps.prepare.outputs.tag }}
      push_tags: ${{ steps.prepare.outputs.push_tags }}
    steps:
      - id: prepare
        uses: TourinhoM/org-ci-platform/.github/actions/prepare-image-tag@main

  # -----------------------------
  # 4️⃣ Docker Build
  # -----------------------------
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: prepare-image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: TourinhoM/org-ci-platform/.github/actions/docker-build-artifact@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}
          dockerfile-path: ./Dockerfile

  # -----------------------------
  # 5️⃣ Trivy Image
  # -----------------------------
  trivy-image:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: [docker-build, prepare-image]
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - run: docker load -i image.tar
      - uses: TourinhoM/org-ci-platform/.github/actions/trivy-image@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}

  # -----------------------------
  # 6️⃣ Docker Push
  # -----------------------------
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs: [trivy-image, prepare-image]
    permissions:
      contents: read
      packages: write
    env:
      LOGIN_USERNAME: ${{ github.actor }}
      LOGIN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: TourinhoM/org-ci-platform/.github/actions/docker-push-artifact@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}
          push-tags: ${{ needs.prepare-image.outputs.push_tags }}
          registry: ghcr.io