name: CI - Tag Release

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string

jobs:

  # -----------------------------
  # 1️⃣ Trivy FS
  # -----------------------------
  trivy-fs:
    name: Trivy FS Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: TourinhoM/org-ci-platform/.github/actions/trivy-fs@main

  # -----------------------------
  # 2️⃣ Prepare Image
  # -----------------------------
  prepare-image:
    name: Prepare image
    runs-on: ubuntu-latest
    needs: trivy-fs
    outputs:
      image_repo: ${{ steps.env.outputs.repo }}
      image_tag: ${{ steps.env.outputs.tag }}
      push_tags: ${{ steps.env.outputs.push_tags }}
    steps:
      - id: env
        run: |
          REPO=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "repo=$REPO" >> $GITHUB_OUTPUT

          TAG="${{ github.ref_name }}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          echo "push_tags<<EOT" >> $GITHUB_OUTPUT
          echo "ghcr.io/$REPO:$TAG" >> $GITHUB_OUTPUT
          echo "ghcr.io/$REPO:latest" >> $GITHUB_OUTPUT
          echo "EOT" >> $GITHUB_OUTPUT

  # -----------------------------
  # 3️⃣ Docker Build
  # -----------------------------
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: prepare-image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: TourinhoM/org-ci-platform/.github/actions/docker-build-artifact@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}
          dockerfile-path: ./Dockerfile

  # -----------------------------
  # 4️⃣ Trivy Image
  # -----------------------------
  trivy-image:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    needs: [docker-build, prepare-image]
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - run: docker load -i image.tar
      - uses: TourinhoM/org-ci-platform/.github/actions/trivy-image@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}

  # -----------------------------
  # 5️⃣ Docker Push
  # -----------------------------
  docker-push:
    name: Docker Push
    runs-on: ubuntu-latest
    needs: [trivy-image, prepare-image]
    permissions:
      contents: read
      packages: write
    env:
      LOGIN_USERNAME: ${{ github.actor }}
      LOGIN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: TourinhoM/org-ci-platform/.github/actions/docker-push-artifact@main
        with:
          image-ref: ghcr.io/${{ needs.prepare-image.outputs.image_repo }}:${{ needs.prepare-image.outputs.image_tag }}
          push-tags: ${{ needs.prepare-image.outputs.push_tags }}
          registry: ghcr.io