# Orchestrator: Tag pipeline (Docker build → Trivy scan → Docker push)
name: CI Tag

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      dockerfile-path:
        required: false
        default: './Dockerfile'
        type: string
      ci-platform-repo:
        required: false
        default: 'YOUR_ORG/org-ci-platform'
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  docker-build:
    name: Docker build (artefato)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ${{ inputs.ci-platform-repo }}/.github/actions/docker-build-artifact@main
        with:
          image-ref: ${{ inputs.image-name }}:${{ github.ref_name }}
          dockerfile-path: ${{ inputs.dockerfile-path }}

  trivy-image:
    name: Trivy container scan
    needs: [docker-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
      - run: docker load -i image.tar
      - uses: ${{ inputs.ci-platform-repo }}/.github/actions/trivy-image@main
        with:
          image-ref: ${{ inputs.image-name }}:${{ github.ref_name }}

  docker-push:
    name: Docker push
    needs: [trivy-image]
    runs-on: ubuntu-latest
    env:
      LOGIN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: ${{ inputs.ci-platform-repo }}/.github/actions/docker-push-artifact@main
        with:
          image-ref: ${{ inputs.image-name }}:${{ github.ref_name }}
          push-tags: |
            ${{ inputs.image-name }}:${{ github.ref_name }}
            ${{ inputs.image-name }}:latest
